- name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git rebase --abort || true
          git fetch origin main
          git checkout main
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-updated health news for today"
          git pull --rebase -X theirs origin main
          git push origin main
